archive:
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: 32-bit
    amd64: 64-bit
snapshot:
  name_template: "{{ .Tag }}-next"
brew:
  github:
    owner: timsolov
    name: homebrew-boilr
  commit_author:
    name: goreleaserbot
  folder: Formula
  homepage: https://github.com/timsolov/boilr
  description: "Boilerplate template manager that generates files or directories from template repositories"
builds:
  - ldflags:
      - -s -w -X 'github.com/timsolov/boilr/pkg/boilr.Version={{.Version}}' -X 'github.com/timsolov/boilr/pkg/boilr.BuildDate={{.Date}}' -X 'github.com/timsolov/boilr/pkg/boilr.Commit={{.Commit}}'
